name: Monitor Legislativo - Diputados
on: [workflow_dispatch]

# AGREGÁ ESTO PARA DARLE PERMISO DE ESCRITURA AL BOT
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Instalar Dependencias
        run: |
          pip install requests beautifulsoup4 pandas
          
      - name: Correr Scraper Diputados
        run: python obtener_datos.py
        
      - name: Verificar y Guardar Cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add nomina_diputados.csv
          if git diff --quiet && git diff --staged --quiet; then
            echo "No hay cambios para subir"
          else
            git commit -m "Actualización automática de nómina"
            git push
          fi
