name: Scraper Senado Pro
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar Chrome y Selenium
        run: |
          pip install selenium beautifulsoup4 webdriver-manager
      - name: Correr Scraper Pro
        run: python scraper_senado_pro.py
